import './globals.css'

//static metadata 
export const metadata = {
  title: "Next.js",
  description: "Generated by nextjs"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header style={{
          background: "lightblue",
          padding: "1rem",
          color: "black"
        }}>
          <p>Header</p>
        </header>
        {children}
      </body>
    </html>
  );
}
